server:
  port: 10002
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://127.0.0.1:10002/eureka/,http://192.168.1.65:10001/eureka/