server:
  port: 10001
eureka:
  instance:
    hostname: 192.168.1.65
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://192.168.1.65:10001/eureka/,http://127.0.0.1:10002/eureka/