server:
  port: 10010
spring:
  application:
    name: ZUUL-CLIENT
  sleuth:
      web:
        client:
          enabled: true
      sampler:
        probability: 1.0
  zipkin:
    base-url: http://127.0.0.1:9411
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/
zuul:
  routes:
    student:
      path: /stu/**
      service-id: STUDENT-CLIENT
    teacher:
      path: /tea/**
      service-id: TEACHER-CLIENT
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS